name: Prod - Deploy APP to FTP

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Check build directory
        run: ls -l ./build

      - name: FTP Deploy
        uses: sebastianpopp/ftp-action@v3
        with:
          ftp-server: projet-efrei.alwaysdata.net
          ftp-username: projet-efrei
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build
          remote-dir: /www
